spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: camadas
          uri: lb://camadas
          predicates:
            - Path=/instance/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://10.0.0.106:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080
  address: 10.0.0.106
